- Import Dependencies

In [4]:
import torch        # import torch library.

c:\Users\simon\iCloudDrive\Downloads\Projects\Project_Apollo\Pro_Humber\Semester04\Deep Learning - ITE-5410\local_lab\Linear_regression\env\lib\site-packages\torch\nn\modules\transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


- Prepare dataset

  - For linear regression, we take `y = 3x + 1`
  - Appart from the features and labels, some noise is needed.
    - `y = 3x + 1 + b`, where `b` stands for bias.

- `tensor`

  - a fundamental data structure. It is a multi-dimensional array that can contain numerical data
  - A tensor is similar to an array or matrix

- Types of tensor
  - A `scalar` is a 0-dimensional tensor (a **single number**).
  - A `vector` is a **1-dimensional** tensor.
  - A `matrix` is a **2-dimensional** tensor.
  - Tensors with more than two dimensions are often referred to as `n-dimensional tensors` or simply `tensors`.


- `manual_seed(seed)`:

  - Sets the seed for generating random numbers.
  - Parameter:
    - `seed`: The desired seed.
  - Returns:
    - a `torch.Generator` object.

- In deep learning, it's common to use random initialization for parameters, and setting the seed allows you to **obtain the same set of random numbers** each time you run your code. This is important for `reproducibility`, especially when you are developing and testing models, as it **helps to eliminate randomness as a factor** when comparing results between different runs.


- `torch.rand(size)` :
  - Returns a **tensor filled with random numbers** from a **uniform distribution** on the interval `[0,1)`
  - Parameter:
    - `size`: a sequence of integers defining the shape of the output tensor.
      - e.g.:
        - `4`: a row of 4 random numbers
        - `(2,3)`: 2 rows of random numbers, and 3 numbers per row.
  - Return:
    - `torch.Tensor`


In [5]:
# Prepare dataset
torch.manual_seed(42)  # Sets the seed for generating random numbers.

X = 2 * torch.rand(100, 1)  # 100 samples, 1 feature, 100 rows of sample
y = 3 * X + 1 + 0.1 * torch.randn(100, 1)  # true relationship with some noise

In [6]:
print(X)

tensor([[1.7645],
        [1.8300],
        [0.7657],
        [1.9186],
        [0.7809],
        [1.2018],
        [0.5131],
        [1.5873],
        [1.8815],
        [0.2664],
        [1.8692],
        [1.1872],
        [1.7388],
        [1.1354],
        [1.4822],
        [0.8588],
        [1.7709],
        [1.1478],
        [0.5332],
        [1.2549],
        [0.5393],
        [0.8827],
        [0.5938],
        [1.6634],
        [0.2106],
        [0.5390],
        [0.7176],
        [0.3987],
        [1.0944],
        [0.0123],
        [1.9031],
        [0.1505],
        [1.7720],
        [1.1664],
        [0.6753],
        [1.6179],
        [1.1559],
        [1.8080],
        [1.1093],
        [0.6846],
        [1.2687],
        [0.7288],
        [1.4209],
        [1.8928],
        [1.5781],
        [0.5628],
        [1.5773],
        [1.1789],
        [1.5078],
        [0.3905],
        [0.0101],
        [0.6136],
        [0.2330],
        [1.8205],
        [1.2880],
        [1

In [7]:
print(y)

tensor([[6.3577],
        [6.5483],
        [3.4039],
        [6.7108],
        [3.2748],
        [4.6628],
        [2.5582],
        [5.7261],
        [6.6711],
        [1.9264],
        [6.6075],
        [4.5311],
        [6.1178],
        [4.4186],
        [5.4816],
        [3.6382],
        [6.3853],
        [4.4525],
        [2.5606],
        [4.8175],
        [2.7209],
        [3.5777],
        [2.8828],
        [5.9570],
        [1.7414],
        [2.6510],
        [3.2249],
        [2.2373],
        [4.2258],
        [1.0876],
        [6.6618],
        [1.4024],
        [6.3025],
        [4.6628],
        [3.0914],
        [5.9115],
        [4.4315],
        [6.4178],
        [4.3353],
        [3.1357],
        [4.7685],
        [3.2898],
        [5.1939],
        [6.7421],
        [5.7559],
        [2.6838],
        [5.5884],
        [4.4801],
        [5.5505],
        [2.1504],
        [0.9570],
        [2.8513],
        [1.8031],
        [6.4216],
        [4.6348],
        [5

- `torch.randn(size, requires_grad=False)` :
  - Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1 (also called the standard normal distribution).
  - Parameter:
    - `size`: a sequence of integers defining the shape of the output tensor.
      - e.g.:
        - `4`: a row of 4 random numbers
        - `(2,3)`: 2 rows of random numbers, and 3 numbers per row.
    - `requires_grad`:
      - Default: `False`.
      - If autograd should record operations on the returned tensor. If true, model will track operations on this tensor for automatic differentiation.
  - Return:
    - `torch.Tensor`


- Initialize model parameters
  - To initialize the parameter, we assign a random number as the init parameters for weight and bias.
  - Since we are wokring on a `y = 3x + 1`, we only have 1 feature and 1 bias. Therefore, the size of w, b are `1`.
  - We need to gradient the w and b, thus `requires_grad` need to be `true`.


In [11]:

# Initialize model parameters (weights and bias)
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print(w)
print(b)


tensor([0.2469], requires_grad=True)
tensor([0.0324], requires_grad=True)


In [9]:

# Hyperparameters
learning_rate = 0.01
num_epochs = 1000

# Training the model
for epoch in range(num_epochs):
    # Forward pass
    y_pred = X.mm(w) + b  # X * w + b

    # Calculate the loss (Mean Squared Error)
    loss = ((y_pred - y).pow(2)).mean()

    # Backward pass
    loss.backward()

    # Update parameters using gradient descent
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

        # Zero the gradients for the next iteration
        w.grad.zero_()
        b.grad.zero_()

    # Print the loss every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

# After training, you can use the learned parameters to make predictions
# For example, predict the value for a new input
new_input = torch.tensor([[2.5]])  # a new input
predicted_output = new_input.mm(w) + b
print(f'Predicted output for input {new_input.item()}: {predicted_output.item()}')

RuntimeError: mat2 must be a matrix