## XOR problem


In [1]:
import torch
import torch.nn as nn

NUM_INPUT = 2
NUM_HIDDEN = 5
NUM_OUT = 1
LR = 0.01
EPOCH = 1000

c:\Users\simon\iCloudDrive\Documents\Github\PyTorch_Deep_Learning_ITE-5410\env\lib\site-packages\torch\nn\modules\transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


## Prepare Data


In [2]:
x = torch.tensor([[1., 1.], [0., 0.], [1., 0.], [0., 1.]])
y = torch.tensor([[0.], [0.], [1.], [1.]])


## Define model


In [3]:
model = nn.Sequential(
    # define input layer to a hidden layer
    nn.Linear(NUM_INPUT, NUM_HIDDEN),
    nn.ReLU(),      # activation func
    # define hidden layer to output layer
    nn.Linear(NUM_HIDDEN, NUM_OUT)
    # can apply activation func here. if not, defuat af will apply.
)

loss_fun = torch.nn.MSELoss()   # use MSE as the loss function

optimizer = torch.optim.Adam(model.parameters(), lr=LR)     # algorithm
# pass the parameter to the optimizer
# since we have 1 hidden layer, parameters are w1, w2, b1, b2.

In [4]:

for epoch in range(EPOCH):
    y_pred = model(x)       # get prediction
    loss = loss_fun(y_pred, y)  # get the loss

    print(f"epoch: {epoch}, loss: {loss.item()}")       # output the loss
    # .item(): Returns the value of this tensor as a standard Python number.

    # reset all GD, Resets the gradients of all optimized torch.Tensor s.
    optimizer.zero_grad()
    loss.backward()             # Computes the gradient of current tensor
    # ajust the paramter, Perform a single optimization step.
    optimizer.step()


epoch: 0, loss: 0.9343337416648865
epoch: 1, loss: 0.8891775012016296
epoch: 2, loss: 0.8467819094657898
epoch: 3, loss: 0.806969165802002
epoch: 4, loss: 0.7699593305587769
epoch: 5, loss: 0.73472660779953
epoch: 6, loss: 0.7010949850082397
epoch: 7, loss: 0.6689873933792114
epoch: 8, loss: 0.6383196115493774
epoch: 9, loss: 0.6090022325515747
epoch: 10, loss: 0.5809432864189148
epoch: 11, loss: 0.5540527105331421
epoch: 12, loss: 0.5282474756240845
epoch: 13, loss: 0.503457248210907
epoch: 14, loss: 0.479628324508667
epoch: 15, loss: 0.45672744512557983
epoch: 16, loss: 0.43474239110946655
epoch: 17, loss: 0.41368141770362854
epoch: 18, loss: 0.39357078075408936
epoch: 19, loss: 0.3744509518146515
epoch: 20, loss: 0.35637253522872925
epoch: 21, loss: 0.33939170837402344
epoch: 22, loss: 0.32356590032577515
epoch: 23, loss: 0.3089498281478882
epoch: 24, loss: 0.29559147357940674
epoch: 25, loss: 0.2835281491279602
epoch: 26, loss: 0.2727821469306946
epoch: 27, loss: 0.2639274299144745

In [5]:
# prediction
y_pred = model(x)
print(y_pred)

tensor([[ 2.2352e-07],
        [-4.0233e-07],
        [ 1.0000e+00],
        [ 1.0000e+00]], grad_fn=<AddmmBackward0>)


In [6]:
for layer in model.parameters():
    print(f"{layer}")

Parameter containing:
tensor([[-0.4797, -0.0278],
        [-0.6809,  0.6809],
        [-1.1663,  1.1766],
        [ 0.2497, -0.1020],
        [ 1.4542, -1.4576]], requires_grad=True)
Parameter containing:
tensor([-0.5920,  0.5812, -0.0223, -0.3972, -0.0073], requires_grad=True)
Parameter containing:
tensor([[ 0.4159,  0.2393,  0.7252, -0.0265,  0.7873]], requires_grad=True)
Parameter containing:
tensor([-0.1391], requires_grad=True)


- output explain

```sh
Parameter containing:   # w1, the parameters of weight for the input to hidden, 5*2, 5 hidden * 2 feature
tensor([[ 0.9250, -0.9250],
       [-0.6403, -0.3083],
       [-1.1184,  1.1062],
       [ 0.8657, -0.8809],
       [-0.4945,  0.2859]], requires_grad=True)
Parameter containing:       # w2, the parameters of weight for the hidden to output, 1*5, 1 output * 5 hidden
tensor([ 0.0132, -0.5322, -0.0052, -0.0107, -0.4866], requires_grad=True)
Parameter containing:       # b1, the parameters of bias for the input to hidden, 1*5, 1 bias * 5 hidden
tensor([[0.6443, 0.1278, 0.9159, 0.4725, 0.2167]], requires_grad=True)
Parameter containing:       # b2, the parameters of bias for the hidden to output, 1*1, 1 output * 1 bias
tensor([-0.0085], requires_grad=True)
```


- To less epoch:
  - more hidden layer
  - lr
  - activation func / loss func
  - algorithm / optimizer
  - more multilayer in the model:
    - more laze+relu
